# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Executable package

on:
  release:
    types: [created, edited]

jobs:
  build:
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install UI deps
        run: npm i
        working-directory: ui
      - name: Install desktop deps
        run: npm i
        working-directory: desktop-app
      - name: Build UI
        run: npm run build
        working-directory: ui
      - name: Build Desktop
        run: npm run make
        working-directory: desktop-app
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: desktop-app/out/make/**/*.dmg
