# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Executable package

on:
  release:
    types: [created, edited]

jobs:
  build:
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i
        working-directory: ui
      - run: npm i
        working-directory: desktop-app
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: desktop-app
        with:
          tag-prefix: "v"
      - run: npm run build
        working-directory: ui
      - run: npm run build
        working-directory: desktop-app
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: desktop-app/out/make/**/*.dmg
