# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Check typing

on:
  push:
    branches:
      - "main"

jobs:
  publish-npm:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Install UI deps
        run: npm i
        working-directory: ui
      - name: Install desktop deps
        run: npm i
        working-directory: desktop-app
      - name: Check UI types
        run: npx tsc --noEmit
        working-directory: ui
      - name: Check Desktop types
        run: npx tsc --noEmit
        working-directory: desktop-app
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: desktop-app
        with:
          tag-prefix: "v"
